[package]
name = "tube"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
tube-inotify = { version = "0.1.0", path = "../tube-inotify" }
